from year_2024.day_08 import antinodes_number, parse_input, resonant_antinodes

text = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

text_2 = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""


def test_antinodes():
    assert antinodes_number(*parse_input(text)) == 14

def test_resonant_antinodes():
    assert resonant_antinodes(*parse_input(text_2)) == 9

def test_resonant_antinodes_bigger():
    assert resonant_antinodes(*parse_input(text)) == 34